books:
    resource: "@BooksBundle/Resources/config/routing.yml"
    prefix:   /

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /

evenement_demandeevenement:
    resource: "@EvenementBundle/Controller/DemandeevenementController.php"
    type:     annotation

evenement_evenement:
    resource: "@EvenementBundle/Controller/EvenementController.php"
    type:     annotation

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /

evenement_club:
    resource: "@EvenementBundle/Controller/ClubController.php"
    type:     annotation


app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }