note_index:
    path:     /
    defaults: { _controller: "schoolBundle:Note:index" }
    methods:  GET

note_show:
    path:     /{etudiant}/show
    defaults: { _controller: "schoolBundle:Note:show" }
    methods:  GET

note_affiche_etudiant:
    path:     /notesetudiant
    defaults: { _controller: "schoolBundle:Note:noteEtudiant" }
    methods:  GET

note_affiche_enseignant:
    path:     /notesenseignant
    defaults: { _controller: "schoolBundle:Note:noteEnseignant" }
    methods:  GET

note_read:
    path:     /read
    defaults: { _controller: "schoolBundle:Note:index" }
    methods:  GET

note_new:
    path:     /add
    defaults: { _controller: "schoolBundle:Note:add" }
    methods:  [GET, POST]

note_edit:
    path:     /{idetudiant}/{idmatiere}
    defaults: { _controller: "schoolBundle:Note:edit" }
    methods:  [GET, POST]

note_delete:
    path:     /{idetudiant}/{idmatiere}/delete
    defaults: { _controller: "schoolBundle:Note:delete" }

