
afficher_user:
    path:     /user/afficher
    defaults: { _controller: UserBundle:User:afficher }

profile_user:
    path:     /user/profile
    defaults: { _controller: UserBundle:User:profile }


