class_absence:
    resource: "@ClassBundle/Resources/config/routing/absence.yml"
    prefix:   /absence
class:
    resource: "@ClassBundle/Resources/config/routing/classe.yml"
    prefix:   /class
emploi:
    resource: "@ClassBundle/Resources/config/routing/emplois.yml"
    prefix:   /emploi
calendar:
    resource: "@ClassBundle/Resources/config/routing/calendarannuel.yml"
    prefix:   /calendar


class_homepage:
    path:     /indexClass
    defaults: { _controller: ClassBundle:Default:index }
affectEtudClass:
    path:     /etds
    defaults: { _controller: ClassBundle:Default:affetudiclass }
affct:
    path:     /affct/{id}
    defaults: { _controller: ClassBundle:Default:affect }
affctense:
    path:     /affctense/{id}/{idmat}
    defaults: { _controller: ClassBundle:Default:affectEnsei }
affctens:
    path:     /ens
    defaults: { _controller: ClassBundle:Default:affenseigclass }

abcenseetud:
    path:     /absetud
    defaults: { _controller: ClassBundle:Default:getAbsence }

empleetud:
    path:     /empletud
    defaults: { _controller: ClassBundle:Default:getEmplois }
pdf:
    path:     /pdf
    defaults: { _controller: ClassBundle:Default:PDF }
projet_indexPdf:
    path:     /Pdfff
    defaults: { _controller: "ClassBundle:Default:indexPdf" }
    methods:  [GET, POST]
search:
    path:     /search
    defaults: { _controller: ClassBundle:Default:liveSearch }
