school_resultat:
    resource: "@schoolBundle/Controller/ResultatController.php"
    type:     annotation

school:
    resource: "@schoolBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"